Hacky fix for incorrect model names trying to be accessed if more than two stars in group
astropy/photutils pull request #1135
Opened 2020-12-21 09:40 UTC by krachyon

After running into https://github.com/astropy/photutils/issues/845 I tried to fix it generically (https://github.com/krachyon/photutils/tree/parameter_name_matching) by comparing the parameter names of the psf model and matching them to those that should be output in `_model_params2table()` but ran into the issue that sometimes a compound model seems to have the parameters combined by adding a postfix (param_i->param_i_j) or by incrementing a existing postfix(param_i -> param_j). More Details on that train of thought in the comment in `photometry.py`

I decided it's not really worth trying to predict that behaviour and came up with this pretty hacky way to handle both. I'm not sure if this is something merge worthy, but for now it seems to solve the issue on my end. 

I guess the proper solution would involve modifying the way that the expected parameter names are derived in the combination of `prepare_psf_model` and `photometry._define_fit_param_names()` `get_grouped_psf_model()`. I suspect in the latter function we could always compare the before-after state, but ideally there should probably be a way to access the parameters of submodels by their original names in a compound model implemented in astropy.

2020-12-21 09:40 UTC, pep8speaks commented
Hello @krachyon! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`photutils/psf/photometry.py`](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py):

> [Line 528:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L528): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 530:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L530): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 531:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L531): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 533:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L533): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 535:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L535): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 537:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L537): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 538:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L538): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 543:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L543): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 544:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L544): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 545:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L545): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 546:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L546): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 551:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L551): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 553:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L553): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 556:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L556): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 557:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L557): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 558:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L558): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 562:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L562): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 565:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/photometry.py#L565): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

* In the file [`photutils/psf/tests/test_photometry.py`](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py):

> [Line 661:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L661): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 673:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L673): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 680:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L680): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 686:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L686): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 695:37](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L695): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 695:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_photometry.py#L695): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)

* In the file [`photutils/psf/tests/test_utils.py`](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_utils.py):

> [Line 15:80](https://github.com/astropy/photutils/blob/94df5f1538e36c288fb82f778d213ec16a2555b4/photutils/psf/tests/test_utils.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)

2020-12-21 09:48 UTC, krachyon commented
So according to tox -e codestyle line length is limited to 100, but the pep8 bot wants 79. What's the correct amount?

2021-01-08 21:55 UTC, larrybradley commented
Thanks, @krachyon.  Since this has been a long-term issue, I'm inclined to merge it and think about if there's a better solution later.  @eteq - would you like to review this?

2021-02-03 17:31 UTC, krachyon commented
Ok, so I managed to trigger this issue again after 'fixing' it and looking at it again I found a solution that's not actually that awful. Instead of trying to soothsay the parameter name, I tagged the models belonging to individual stars during combination so that later we just have to look for the name.

2021-03-15 19:01 UTC, larrybradley requested changes
Thanks, @krachyon.  I'm not an expert in this part of the code, but since this fixes the issue I'm inclined to merge it.  I left a couple style comments.

Can you also please add a changelog entry in the v1.1.0 Bug Fixes section under `photutils.psf`?

2021-03-17 00:14 UTC, larrybradley approved these changes
Thanks again, @krachyon.

2021-03-17 00:14 UTC, merged