Fix issue #1174 (divisioin by zero in gradient computation)
astropy/photutils pull request #1180
Opened 2021-03-10 14:51 UTC by ibusko

2021-03-10 20:51 UTC, ibusko commented
The CI tests that get cancelled seem to be running into a timeout. Most of them stop when running `test_ellipse`. When I run `tox` on my computer I can see that they eventually pass. I believe this is related to issue #1168. Not only `build_model`, but the core sampling algorithm is `fit_ellipse` should be made faster by using Cython.

2021-03-15 18:41 UTC, larrybradley commented
It looks like the tests failed to due an internet timeout.  I've restarted them.  Let's see what happens.

2021-03-15 18:42 UTC, larrybradley approved these changes
Thanks, @ibusko.

2021-03-15 18:43 UTC, larrybradley requested changes

2021-03-15 18:43 UTC, larrybradley commented on CHANGES.rst
> +  - Fix computation of gradient relative error when gradient=0
```suggestion
  - Fix computation of gradient relative error when gradient=0. [#1180]
```

2021-03-15 18:43 UTC, larrybradley approved these changes

2021-03-15 19:16 UTC, larrybradley commented
@ibusko This is a real test failure.  I can reproduce the test failure locally.  The failed test is in `test_fitter.py` in the `TestM51.test_m51()` method.  This test loads the remote `M51.fits` image, so to run it locally add the `--remote-data=any` flag:  `pytest --remote-data-any`.  Specifically, `isophote.intens` is now returning 155.046967 when 156.3 is expected:  https://github.com/astropy/photutils/pull/1180/checks?check_run_id=2115521635#step:7:276

2021-03-15 19:50 UTC, larrybradley approved these changes
Thanks, @ibusko!

2021-03-15 19:50 UTC, merged