add function to create GriddedPSFModel from EPSFs
astropy/photutils pull request #1596
Opened 2023-07-28 02:37 UTC by cshanahan1

(This is replacing #1584)

This PR adds a function to psf.utils to create a GriddedPSFModel from a list of EPSF models.

2023-07-28 14:07 UTC, cshanahan1 commented
@larrybradley this is ready for review, I responded to your comments in the last PR. the tests are skipped temporarily since they download data - I will replace this in a follow up PR. the tests pass locally.

2023-08-01 21:18 UTC, larrybradley requested changes

2023-08-01 21:18 UTC, larrybradley commented on photutils/psf/tests/test_utils.py
> +@pytest.mark.skip(reason="Skipping for CI temporarily, passes locally.")
```suggestion
@pytest.mark.remote_data
```

This should allow the CI tests to pass with remote data.  Locally you can run `tox -e test -- --remote-data=any` to test this.

2023-08-07 14:45 UTC, cshanahan1 commented
@larrybradley are we ok with the test coverage or do you want me to add more tests? the untested lines are mostly just some input type checks i put in. other than that, i think this is ready to merge?

2023-08-07 17:55 UTC, larrybradley approved these changes
Thanks, @cshanahan1

2023-08-07 17:55 UTC, merged