Add option to exclude local background in residual image (#1690)
astropy/photutils pull request #1691
Opened 2024-01-10 13:54 UTC by m-samland

This pull request is to solve issue #1690. I added a new keyword to the function `make_model_image' and `make_residual_image' of the PSFPhotometry-class to toggle whether the local background model is included or not.

> At the moment it is only possible to make a model image of the fitted PSF Photometry that includes the locally measured background for each star. However, when there is highly structures background and a crowded field, it may be desirable to only subtract a model of the fit stars from the image, without the local background estimate (that currently can only be a scalar). Otherwise we have overlapping regions of subtracted scalar backgrounds in the residual image when stars are close to each other.
> This option may also be useful for iterative PSF fitting of clustered stars.
> The solution would simply to add one more parameter ``include_bkg'' to both functions in the PSFPhotometry-class.

The changes should not break existing code, as far as I can tell.

2024-01-18 17:35 UTC, larrybradley requested changes
Thanks, @m-samland.  I have just a few suggested changes.

2024-01-18 17:35 UTC, larrybradley commented on photutils/psf/photometry.py
> +    def make_model_image(self, shape, psf_shape, include_bkg=True):
```suggestion
    def make_model_image(self, shape, psf_shape, include_localbkg=True):
```

2024-01-18 17:35 UTC, larrybradley commented on photutils/psf/photometry.py
> +        include_bkg : bool, optional
```suggestion
        include_localbkg : bool, optional
```

2024-01-18 17:35 UTC, larrybradley commented on photutils/psf/photometry.py
> +    def make_residual_image(self, data, psf_shape, include_bkg=True):
```suggestion
    def make_residual_image(self, data, psf_shape, include_localbkg=True):
```

2024-01-18 17:35 UTC, larrybradley commented on photutils/psf/photometry.py
> +        include_bkg : bool, optional
```suggestion
        include_localbkg : bool, optional
```

2024-01-18 17:35 UTC, larrybradley commented on photutils/psf/photometry.py
> +            residual = self.make_model_image(data.shape, psf_shape, include_bkg)
```suggestion
            residual = self.make_model_image(data.shape, psf_shape, 
                                             include_localbkg=include_localbkg)
```

2024-01-18 17:37 UTC, larrybradley commented on photutils/psf/photometry.py
> +            residual.data[:] = self.make_residual_image(data.data, psf_shape, include_bkg)
```suggestion
            residual.data[:] = self.make_residual_image(data.data, psf_shape, 
                                                        include_localbkg=include_localbkg)
```

2024-02-12 15:20 UTC, pep8speaks commented
Hello @m-samland! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`photutils/psf/photometry.py`](https://github.com/astropy/photutils/blob/50c1b4acedaf2289d1814ef4703b0c10aa1f7a77/photutils/psf/photometry.py):

> [Line 1075:16](https://github.com/astropy/photutils/blob/50c1b4acedaf2289d1814ef4703b0c10aa1f7a77/photutils/psf/photometry.py#L1075): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'include_bkg'

2024-02-12 15:28 UTC, m-samland commented
Thanks for the suggestions @larrybradley, I commited them. Happy to have this merged. :)

2024-02-13 03:21 UTC, larrybradley approved these changes
Thanks again, @m-samland.  This needs a test and a changelog entry, but I'll add those in a followup PR.  I'm also considering making the default be to not include the local background subtraction (unfortunately that would be a breaking change, but it might be sensible).

2024-02-13 03:35 UTC, merged

2024-05-01 20:04 UTC, SterlingYM commented
Can the same feature (to turn off local bkg) be supported for ```IterativePSFPhotometry``` class too?

https://github.com/astropy/photutils/blob/d78f2acde625a8f526c99fd0fa021f52bfe7297f/photutils/psf/photometry.py#L1550C1-L1550C60

2024-05-01 20:22 UTC, larrybradley commented
@SterlingYM Yes, I'll add that feature to `IterativePSFPhotometry`.  Thanks!

2024-05-24 20:53 UTC, larrybradley commented
@SterlingYM This was added in #1756.