Include interval ends for sharpless, roundness, and peakmax
astropy/photutils pull request #1978
Opened 2024-12-30 09:20 UTC by mcara

Closes #1977

This PR modifies selection of sources by shapness, roundness, and peakmax to include the interval ends, i.e., that sources that have roundness 0.0 are selected instead of being rejected when `sharplo=0.0`.

2025-01-02 16:37 UTC, larrybradley commented
@mcara Do you recall what the old IRAF routines use?  This is a breaking change, but I suppose *could* be classified as a bug.

2025-01-03 05:21 UTC, mcara commented
Sorry, I replied in the issue: https://github.com/astropy/photutils/issues/1977#issuecomment-2568689761

2025-01-03 06:41 UTC, mcara commented
> This is a breaking change...

This could break some idealized tests, just like the one I am using in https://github.com/astropy/photutils/issues/1977 but in practice, what is the chance to have a perfectly round star (or a star with ellipticity precisely 2) in real observations? So, I believe this PR will have a minor effect, except for helping avoid this kind of tricks: https://github.com/spacetelescope/jwst/blob/6d0c2d50c72d32f9a16bf30264d3528bff53e36e/jwst/tweakreg/tests/test_tweakreg.py#L99 which seem unnatural given that the lower limit for roundness is 0 (it cannot be negative in the original IRAF code) yet I _have to_ set this limit to a negative value in order to include 0.

2025-01-03 15:44 UTC, larrybradley requested changes
LGTM.  The old IRAF tools also allowed values at the limits.

Could you also please add a test for `DAOStarFinder`?

2025-01-03 15:44 UTC, larrybradley commented on CHANGES.rst
> +  - Detected sources that match interval ends for sharpnes, roundness, and
```suggestion
  - Detected sources that match interval ends for sharpness, roundness, and
```

2025-01-03 15:45 UTC, larrybradley commented
This also needs to be rebased due to a conflict in the changelog.

2025-01-03 17:43 UTC, larrybradley approved these changes
Thanks, @mcara.  The test failure is unrelated to this PR.

2025-01-03 17:45 UTC, merged